default_context:
  project_name: 'CTest'
  project_slug: 'ctest'
  domain_main: 'ctest.com'
  domain_staging: 'stag.ctest.com'
  docker_swarm_stack_name_main: 'ctest-com'
  docker_swarm_stack_name_staging: 'stag-ctest-com'
  secret_key: 'rjfn4uf04f34f'
  first_superuser: 'admin@ctest.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ctest.com", "https://stag.ctest.com", "https://ctest.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@ctest.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: 'ctest.com'
  traefik_constraint_tag_staging: 'stag.ctest.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
